---
- name: Install qemu-guest-agent package
  hosts: all
  
  tasks:
    - name: Install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
      become: yes
      become_user: kolibri
