---
- name: Install qemu-guest-agent package
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
